# Generated by Django 4.2.6 on 2024-01-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_name_en_us_category_name_jp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_jp',
            new_name='name_ja',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_jp',
            new_name='text_ja',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_jp',
            new_name='title_ja',
        ),
    ]
